services:
  yt_pod_service:
    image: yt_pod_image
    build: 
      dockerfile: Dockerfile 
      target: development
    networks:
      - yt_pod_network
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./src 
        target: /app/src
    env_file:
      - ./.env
  
  redis:
    image: redis:alpine
    container_name: yt_pod_redis
    networks:
      - yt_pod_network
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: unless-stopped
   

volumes:
  redis-data:
networks:
  yt_pod_network: