services:
  yt_pod_service:
    image: yt_pod_image
    build: 
      dockerfile: Dockerfile 
      target: development
    networks:
      - yt_pod_network
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./src 
        target: /app/src
    env_file:
      - ./.env

networks:
  yt_pod_network: