name: Youtube Transcript Pod Continuous Deployment Workflow

on:
    push:
        branches: [main]

jobs:
    build_and_push_docker_images:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code:
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: Set Up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Buildx
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Extract Metadata For Image
              id: meta-id
              uses: docker/metadata-action@v4
              with:
                images: ${{ secrets.DOCKER_USERNAME }}/yt_pod
                tags: |
                    type=ref,event=branch
                    type=semver,pattern={{version}}
                    type=sha,format=short
                    latest
            
            - name: Build and Push Yt-Pod Image
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ${{ steps.meta-id.output.tags }}
                labels: ${{ steps.meta-id.output.labels }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
